name: Build and Deploy Plugin

on:
  push:
    branches:
      - main  # Ana branch üzerinde değişiklik yapıldığında tetiklenecek.

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu üzerinde çalışacak.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build the plugin
        run: ./gradlew SezonlukDizi:make  # Plugin’i derlemek için komut.

      - name: Deploy to Android
        run: ./gradlew SezonlukDizi:deployWithAdb  # Plugin’i Android’e dağıtmak için komut.
