name: Automatic Merge

on:
  push:
    branches:
      - main  # Ana branş, burada değişiklik yapıldığında tetiklenecek

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Merge domain-degisikligi into main
        run: |
          git checkout main
          git merge domain-degisikligi
          git push origin main
