name: Temizlik İşlemi

on:
  workflow_run:
    workflows: ["Prebuild Workflow"]  # Bu, prebuild workflow'undan sonra çalışacak
    types:
      - completed
  workflow_dispatch:

jobs:
  clean_up:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Actions ortamını temizle
        run: |
          echo "Geçici dosyalar temizleniyor..."
          sudo apt-get clean
          sudo apt-get autoremove -y
          rm -rf ~/.cache/*

          # Git deposunun var olup olmadığını kontrol et
          if [ -d ".git" ]; then
            echo "Git deposu bulundu. Git temizliği yapılıyor..."
            git gc --prune=now
            git clean -fdx
          else
            echo "Git deposu bulunamadı, git temizliği yapılmadı."
          fi

      - name: Geçici Derleme Çıktılarını Temizle
        run: |
          echo "Geçici derleme çıktıları temizleniyor..."
          rm -rf build/ dist/ .tox/ .nox/ .coverage/ *.egg-info .eggs

      - name: Cache Temizleme
        run: |
          echo "GitHub Actions cache temizleniyor..."
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/caches"

      - name: Artifaktları Temizle
        run: |
          echo "GitHub Actions artifaktları temizleniyor..."
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts"

      - name: Log Dosyalarını Temizle
        run: |
          echo "Log dosyaları temizleniyor..."
          sudo rm -rf /tmp/* || true

      - name: Eski Workflow Artefaktlarını Temizle
        run: |
          echo "Eski workflow artefaktları temizleniyor..."
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/{workflow_id}/runs"
